# Generated by Django 5.2.17 on 2026-09-30 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Makanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_makanan', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('lokasi_pengambilan', models.CharField(max_length=255)),
                ('batas_layak_konsumsi', models.DateTimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('pemberi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makanan_dibagikan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
