# Generated by Django 5.2.17 on 2026-09-28 16:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FURNITURE', 'Furnitur & Perabot Kos'), ('ELECTRONICS', 'Elektronik & Gadget'), ('BOOKS', 'Buku & Alat Tulis'), ('CLOTHING', 'Pakaian & Aksesori'), ('KITCHEN', 'Peralatan Dapur'), ('OTHER', 'Lain-lain')], default='OTHER', max_length=30)),
                ('condition', models.CharField(choices=[('BRAND_NEW', 'Baru / Belum Pernah Dipakai'), ('LIKE_NEW', 'Seperti Baru (Mulus)'), ('GOOD', 'Layak Pakai'), ('FAIR', 'Ada Minus (Berfungsi)')], default='GOOD', max_length=30)),
                ('is_free', models.BooleanField(default=False, help_text='Centang jika barang dihibahkan secara gratis')),
                ('price', models.DecimalField(decimal_places=0, default=0, help_text='Harga dalam Rupiah (0 jika gratis)', max_digits=12)),
                ('image_url', models.URLField(blank=True, help_text='Tautan foto barang', max_length=500, null=True)),
                ('pickup_location', models.CharField(default='Perpustakaan Pusat UI', help_text='Titik temu / COD kampus', max_length=255)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Tersedia'), ('RESERVED', 'Dipesan'), ('SOLD', 'Terjual / Diberikan')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
