# Generated by Django 5.2.17 on 2026-09-30 09:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama barang yang dipinjamkan (misal: Jas Lab Kimia Ukuran L)', max_length=200)),
                ('description', models.TextField(help_text='Deskripsi detail, kelengkapan, dan ketentuan khusus dari pemilik')),
                ('category', models.CharField(choices=[('ACADEMIC', 'Akademik & Formal (Jas Almamater, Toga, Kemeja)'), ('TRAVEL', 'Travel & Koper (Koper, Carrier, Tas Gunung)'), ('ELECTRONICS', 'Elektronik & Aksesori (Kalkulator, Adapter, Kabel)'), ('TOOLS', 'Peralatan & Hobi (Perkakas Kos, Alat Olahraga, Musik)'), ('OTHER', 'Lain-lain')], default='OTHER', max_length=30)),
                ('condition', models.CharField(choices=[('LIKE_NEW', 'Sangat Baik (Mulus)'), ('GOOD', 'Baik / Layak Pakai'), ('FAIR', 'Ada Minus (Tetap Berfungsi)')], default='GOOD', max_length=30)),
                ('max_duration_days', models.PositiveIntegerField(default=7, help_text='Batas maksimal peminjaman (dalam hari)')),
                ('deposit_fee', models.DecimalField(decimal_places=0, default=0, help_text='Uang jaminan/deposit dalam Rupiah (0 jika tanpa deposit)', max_digits=12)),
                ('pickup_location', models.CharField(default='Perpustakaan Pusat UI', help_text='Titik temu serah-terima barang di area kampus UI', max_length=255)),
                ('image_url', models.URLField(blank=True, help_text='Tautan foto barang', max_length=500, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Tersedia'), ('BORROWED', 'Sedang Dipinjam'), ('UNAVAILABLE', 'Tidak Tersedia')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(help_text='Tanggal mulai peminjaman')),
                ('end_date', models.DateField(help_text='Jadwal pengembalian yang diajukan')),
                ('actual_return_date', models.DateField(blank=True, help_text='Tanggal aktual barang dikembalikan', null=True)),
                ('notes', models.TextField(blank=True, help_text='Alasan peminjaman / pesan untuk pemilik barang')),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Persetujuan Pemilik'), ('APPROVED', 'Disetujui'), ('REJECTED', 'Ditolak'), ('ONGOING', 'Sedang Berlangsung / Barang Sudah Diambil'), ('RETURNED', 'Sudah Dikembalikan'), ('CANCELLED', 'Dibatalkan')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='saling_pinjam.borrowitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
